name: 'GitHub Actions result'

on:
  push:
    branches: 
      - main
#  schedule:
 #  - cron: '20 * * * *'
jobs:
  result-spider:
    runs-on: ubuntu-latest
    steps:
      - name: set_time
        run: |
          cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
          date
      - name: Checkout
        uses: actions/checkout@v2
      - name: 'Working'
        timeout-minutes: 350
        run: |
          wget -c --no-check-certificate https://ookk.gq/tb.zip
          unzip tb.zip
          rm tb.zip
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "$(date +%Y%m%d%H%M%S)" -a
      - name: 'Push changes'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
